# 公共配置文件
spring:
  # session 配置
  session:
    # TODO 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 1天过期
    timeout: 86400

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiao_cg
    username: root
    password: root

# Redis 配置
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456

server:
  address: 0.0.0.0
  port: 8120
  servlet:
    context-path: /api
    # cookie 1天过期
    session:
      cookie:
        max-age: 86400

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 对象存储
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx